// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwAsQYI4Q-2kY6zwfZxhoQ1ycBoDYap80',
    appId: '1:36388404914:web:772d992f6be1f5f00a53ab',
    messagingSenderId: '36388404914',
    projectId: 'flutterapplication2-36303',
    authDomain: 'flutterapplication2-36303.firebaseapp.com',
    storageBucket: 'flutterapplication2-36303.appspot.com',
    measurementId: 'G-PE1SMXNZLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc32UtlKZ_sWf5OYPM1kiOLCjFKBbrgqg',
    appId: '1:36388404914:android:dbdd487e1f9b8c030a53ab',
    messagingSenderId: '36388404914',
    projectId: 'flutterapplication2-36303',
    storageBucket: 'flutterapplication2-36303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8sC9_7wj6MHDn2aE5Se1TqMl-lKIkwDE',
    appId: '1:36388404914:ios:3a53369adc69f4690a53ab',
    messagingSenderId: '36388404914',
    projectId: 'flutterapplication2-36303',
    storageBucket: 'flutterapplication2-36303.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8sC9_7wj6MHDn2aE5Se1TqMl-lKIkwDE',
    appId: '1:36388404914:ios:9ded604b1dbd4bf60a53ab',
    messagingSenderId: '36388404914',
    projectId: 'flutterapplication2-36303',
    storageBucket: 'flutterapplication2-36303.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
